# Generated by Django 4.0.5 on 2022-06-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('cpf', models.IntegerField(max_length=120)),
                ('rg', models.IntegerField(max_length=120)),
                ('phone', models.IntegerField()),
                ('dateOfBirth', models.DateField()),
            ],
        ),
    ]
