# Generated by Django 4.0.5 on 2022-06-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_roles_alter_guardian_cpf_alter_guardian_rg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=120)),
                ('number', models.CharField(blank=True, max_length=120)),
                ('complement', models.CharField(blank=True, max_length=120)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('zipcode', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('cpf', models.IntegerField()),
                ('rg', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('dateOfBirth', models.DateField()),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.address')),
            ],
        ),
    ]
