# Generated by Django 4.0.5 on 2022-06-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_address_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.guardian'),
        ),
    ]
