# Generated by Django 4.0.5 on 2022-06-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_students_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='complement',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='neighborhood',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='number',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='número',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='zipcode',
            new_name='rua',
        ),
    ]
