# Generated by Django 4.0.5 on 2022-06-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_rename_name_guardian_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='name',
            new_name='função',
        ),
    ]
