# Generated by Django 4.0.5 on 2022-06-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_rename_name_roles_função'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='adress',
            new_name='endereço',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='guardian',
            new_name='professor',
        ),
        migrations.RemoveField(
            model_name='students',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='students',
            name='phone',
        ),
        migrations.AddField(
            model_name='students',
            name='data_de_nascimento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='students',
            name='telefone',
            field=models.IntegerField(blank=True, default=111111111),
        ),
        migrations.AlterField(
            model_name='students',
            name='cpf',
            field=models.IntegerField(blank=True, default=111111111),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='students',
            name='rg',
            field=models.IntegerField(blank=True, default=111111111),
        ),
    ]
