# Generated by Django 4.0.5 on 2022-06-29 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_rename_adress_students_endereço_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='endereço',
        ),
        migrations.RemoveField(
            model_name='students',
            name='professor',
        ),
    ]
